### ISSUE TITLE
노션을 통한 문서화 대안 선정

### ISSUE THREAD

**Issue by mainmethod0126** [allqueue/allqueue.github.io#11]
노션 무료버전 더 이상 사용 불가, 이에 대한 대안 필요

## 대안 1 : 깃허브 페이지 (기술 블로그) 로 옮기는 방안

이슈
- public이라 주소지를 알면 외부인원이 내용 확인 가능하여 비밀 정보 암호, 연락처 등 입력 불가 (단, 구글 검색 등록되어있지 않아 정확한 주소를 입력하지 않으면 접근이 힘듬)
- 빈번한 수정 및 동시 수정이 힘듬 가령 `회의록` 작성이 불편함

## 대안 1 이슈에 대한 의견
비밀번호등의 민감 데이터는 노션으로 공유하고 (민감데이터만 저장하면 충분할 것으로 보임)

`기능 명세서류`의 도큐먼트의 경우 -> github page (블로그)
주에 고정으로 한개씩 신규 생성되는 `회의록`의 경우 -> github projects 백로그 (+이터레이션)

으로 관리하는 방법을 제시합니다.

물론 노션보다는 빈번한 수정 및 동시 수정에 대한 불편함이 있지만 한번 해보는 것도 괜찮을 것 같습니다.

다른 의견 있으시면 댓글써주세영~

**Comment by JasonLee228** [comment]
깃허브 블로그로 이관하기 위한 신규 이슈를 생성했습니다.

**Comment by mainmethod0126** [comment]
추가 의견이 없기에 일단 깃허브로 이관을 진행합니다
