### ISSUE TITLE
기능 명세서 이관

### ISSUE THREAD

**Issue by JasonLee228** [allqueue/allqueue.github.io#18]
노션의 기능 명세서를 깃허브 블로그로 이관합니다.

노션 url : https://www.notion.so/d475e36211d84fd2b91dd3b4706d264c

* 기능 명세서
  * TOP NAV
    * 게임 셀렉터
    * 로그인 버튼
    * 로그아웃 버튼
    * BI
  * 홈 화면
    * 게임 매칭 버튼
    * 플레이어 리스트
    * 플레이어 검색
    * 검색 필터 - 선호 포지션
    * 검색 필터 - 정렬
  * 로그인 화면
    * 소셜 로그인
  * 사용자 프로필 화면
    * 신규 프로필 작성
    * match click -> 프로필 입력
  * 매칭 prepare 화면
    * 모드 선택
    * 역할 선택
    * 매칭 버튼
    * progress
    * 매칭 취소
  * 팀 채팅 화면
    * 팀 프로필 리스트
    * 프로필 자세히 보기
    * 채팅
    * 나가기

**Comment by mainmethod0126** [comment]
5월 8일 예정된 주간 미팅에서 확인 후 넘기겠습니다
