### ISSUE TITLE
REST API Response 규격 정하기

### ISSUE THREAD

**Issue by mainmethod0126** [allqueue/allqueue.github.io#26]
API Response 규격을 정해야할 것 같습니다

### status : any
GET /game/info

```json
{
 "code" : 123,
 "detail" : {
   "name" : "lol",
   "code" : 1,
   "etc" : "~~~"
 }
 "message" : ""
}
```

### status : 200

GET /game/info

```json
{
   "name" : "lol",
   "code" : 1,
   "etc" : "~~~"
}
```

### status : 400 ~ 500

GET /game/info

```json
{
 "code" : 123,
 "detail" : {
   "stack" : "~~"
   "exception" : "internal server error" 
 }
 "message" : "internal server error"
}
```

---

예시1, 2중 선택해주시거나 새로운 의견 있으시면 의견 부탁드리겠습니다!

**Comment by mainmethod0126** [comment]
저는 2번에 한표입니다

**Comment by JasonLee228** [comment]
저는 1번에 한표 하겠습니다
아니면 code, data 정도만 고정, msg 는 유동적으로 가도..
성공의 경우는 msg 가 어차피 "success" 값일 거니 딱히 쓰이지는 않겠지만요

**Comment by DaYoung-woo** [comment]
저도 1번이 좋은 것 같습니당!

**Comment by mainmethod0126** [comment]
1번으로하되,

code 는 숫자로,
규격은 protobuf 해서 모든 서버스가 enum 에 대해서 공유할 수 있도록

**Comment by JasonLee228** [comment]
{
 "code" : 0,
 "message" : "SUCCESS",
 "detail" : {
   "name" : "lol",
   "code" : 1,
   "etc" : "~~~"
 }
}

apiResponse.proto

{
 code : int,
 message : String
 detail: json
}

* apiResponse 를 proto 규격으로 할 수 있는가?
-> 확인 필요
generic 타입..........
 -> 굳이

- 각 code / message 규격만 미리 정해놓기 (enum)

**Comment by mainmethod0126** [comment]
https://allqueue.github.io/api-docs/rest-api-response-rules 에 문서화하였습니다.
