### ISSUE TITLE
Github repo 협업 규약 정하기

### ISSUE THREAD

**Issue by mainmethod0126** [allqueue/allqueue.github.io#32]
github repo에 대한 협업 규약을 정해야합니다.

## Fork OK? NO?
- **기본적으로 조직의 private 레포의 경우 정보 유출을 방지하기 위해서 fork 가 비활성화 되어있습니다**, 이를 활성하시켜 fork 를 해서 쓸 것인지 아니면 그냥 그대로 비활성화인채로 쓸 것인지 정해야합니다
>조직에서 리포지토리를 포크하는 기능을 사용하지 않도록 설정하여 중요한 정보가 노출되는 것을 방지할 수 있습니다. 자세한 내용은 "[조직에서 데이터 유출을 방지하기 위한 모범 사례](https://docs.github.com/ko/code-security/getting-started/best-practices-for-preventing-data-leaks-in-your-organization)"을(를) 참조하세요.) 위 내용의 전문은 [여기](https://docs.github.com/ko/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-forking-policy-for-your-repository) 에서 확인 가능합니다.
- 비활성화를 그대로 쓴다면, 브랜치에 바로 커밋 후 main 에 pr할 것인지?

## 브랜치 이름 작성 규칙
- (블로그 포스팅에 사용되는 브랜치 생성 규칙)[https://allqueue.github.io/common/blog-posting-guide/posting-pr-guide] 을 그대로 따를 것인가? 아니면 별도의 규칙을 만들 것인가

## 커밋 메시지 작성 규칙
- 커밋 메세지에 대한 규격은 어떻게 할 것인지? 

## 고정 브랜치와 유동 브랜치 정하기
- 고정 브랜치(삭제 불가) : main, dev
- 유동 브랜치(삭제 가능) : feature, fix(bug)

**Comment by JasonLee228** [comment]
### 고정 브랜치
main
dev

### 유동적 브랜치(기능별?)
feature-1234
feature-1234

### 브랜치명

* task number/작업 태그/task name

#### 작업 태그
* feature
* fix
* test
* chore(코드 변경 없이 설정만을 변경한 경우)
* style
* doc
* refactor
* ...

#### example
* 16/feature/login
* 32/fix/login-error

**Comment by JasonLee228** [comment]
## 커밋메시지 작성규칙

* ADD
* UPDATE
* DELETE

example
```
ADD ~~~ 함수 추가
```
```
UPDATE ~~~해서 함수 ~~~ 변경
```
```
DELETE ~~~ 함수를 삭제했습니다
```

**Comment by JasonLee228** [comment]
### 브랜치 PR 순서

* feature -> dev -> main


### PR 메시지같은 건 별도로 알아서

### dev -> main 의 PR은 신 우 섭 대장님께서 집도
* 뭐 회의는 합니다

**Comment by mainmethod0126** [comment]
http://localhost:3000/github-repo-collaboration-guidelines/branch-create-rules 에 문서화하였습니다

**Comment by limsoeun** [comment]
@mainmethod0126  작업 태그 create 추가했습니다.
